### ISSUE TITLE
Mobile Authentication using Microsoft App Center

### ISSUE THREAD

**Issue by ttirrell** [claudiosanchez/OctoberXamarinChallenge#10]
Title: Mobile Authentication using Microsoft App Center
Author Name: Trevor Tirrell
Twitter Handle: [@trevortirrell](https://twitter.com/TrevorTirrell)
Date: Oct 27
Abstract: Adding authentication to your app couldn't be easier with the new Auth feature for iOS and Android.  We will walk through the setup for this new feature by creating a tenant in Azure and from there we can add authentication to our app with just one line of code.

**Comment by claudiosanchez** [comment]
@ttirrell  - Your article has been approved. Please be aware that we have moved the challenge to the month of October; please confirm the new date for your article.

**Comment by ttirrell** [comment]
Dates are fine.  Thanks

Oct 27

**Comment by claudiosanchez** [comment]
Thanks for your contribution. Please stay tuned, we will be doing a Live Stream to showcase all of the contributions. I will be tweeting the details in the next 48 hours.
