### ISSUE TITLE
Unit testing: The way I test my ViewModels

### ISSUE THREAD

**Issue by MookieFumi** [claudiosanchez/OctoberXamarinChallenge#13]
Title: **Unit testing: The way I test my ViewModels**
Author Name: Miguel Angel Martin Hrdez
Twitter Handle: @mookiefumi
Date: Oct 29
Abstract: I want to share with you how I test my ViewModels, I mean, how I cover them with unit testing so I'll write about:

* Why I make unit testing?
* Which is my perfect combo to get success with unit testing? XUnit, FluentAssertions and Moq.
* What are the available tooling in Visual Studio for Mac to work with unit testing? Alternatives with Visual Studio Code.
* How I integrate the unit testing in my Devops pipeline? *Only If I have enough time*

**Comment by saamerm** [comment]
If possible could you also add, How to add a Github action that runs the unit tests as soon as commit is made?

**Comment by MookieFumi** [comment]
> @saamerm  If possible could you also add, How to add a Github action that runs the unit tests as soon as commit is made?

As I wrote in the description: _Only If I have enough time_, because I'm not having too much free time last weeks.

**Comment by MookieFumi** [comment]
Hi @claudiosanchez

Could you have time to update the calendar with my selected date?  

Thanks!

**Comment by claudiosanchez** [comment]
Hi @MookieFumi - Are you planning on submitting your PR before Wednesday? We will be doing a YouTube Live Stream showcasing all of the content submitted.

**Comment by MookieFumi** [comment]
Hi @claudiosanchez 
Yes, tomorrow morning (Spain) I'll publish my challenge post and after that I'll submit the PR.

Indeed, the "post" is composed by 3 single post.

**Comment by MookieFumi** [comment]
Ah! Sorry I forgot it, could you retweet these related posts with my post challenge?

**Unit testing tools using your MacOS terminal**
https://twitter.com/mookiefumi/status/1188833022189035520?s=21

**Unit testing tools using VSCode**
https://twitter.com/mookiefumi/status/1188772571346542593?s=21

Is it ok for you?

Thanks!

**Comment by claudiosanchez** [comment]
Sure thing :) I'd be happy to.

**Comment by MookieFumi** [comment]
@claudiosanchez [I've just submitted the PR](https://github.com/claudiosanchez/OctoberXamarinChallenge/pull/19) with my posts.

Check it out.
