### ISSUE TITLE
Designing for Actionable Analytics with Xamarin

### ISSUE THREAD

**Issue by saamerm** [claudiosanchez/OctoberXamarinChallenge#14]
**Title:** Designing for Actionable Analytics with Xamarin  
**Author Name:** Saamer Mansoor  
**Twitter Handle:** @saamerm  
**Date:** Oct 24  
**Abstract:**  You need analytics to see how well your app is doing but there's so many possibilities so you don't know the best way to do this. We will walk through analytics strategies used by Forbes 500 companies, to collect data from customers to understand where to focus developer and redesigning resources, while showing real world examples of the analytics at work. Most of the stuff will be generic between Xamarin Forms and Native, but we will also talk about the nuances while working with some pesky native controls in Xamarin Native.

**Comment by claudiosanchez** [comment]
Hi @saamerm - Are you planning on submitting your PR before Wednesday? We will be doing a YouTube Live Stream showcasing all of the content submitted.

**Comment by saamerm** [comment]
Yes I am working on it. Pretty long, but almost done https://medium.com/@prototypemakers/good-analytics-practices-for-xamarin-ios-android-apps-223fcd3634f0
I will be cutting stuff from there and putting stuff into an MD file in your repo
