### ISSUE TITLE
Release made easy with Appcenter

### ISSUE THREAD

**Issue by RaulMonteroC** [claudiosanchez/OctoberXamarinChallenge#2]
**Title:** Release made easy with Appcenter
**Author:** Name: Raul Montero
**Twitter Handle:** @RaulMonteroC
**Date:** October 5
**Abstract:** After you spent all your time and energy working on your application, it is time to release it to the wild, to the users. With Appcenter we can automatize the process by creating a continuous delivery pipeline that releases a new version of the app on every commit to master or even a development brach if we desire to release to alpha/beta channels or beta testers. Never again releasing will be a delicate or hard-to-do process.

**Comment by claudiosanchez** [comment]
@RaulMonteroC - Your article has been approved. Please be aware that we have moved the challenge to the month of October; please confirm the new date for your article.

**Comment by RaulMonteroC** [comment]
@claudiosanchez Noted. I'll update it to October 10.

**Comment by claudiosanchez** [comment]
@RaulMonteroC Hi there. I have not seen your pull request come in. it was scheduled for Oct 5. Are you still going to submit one?

**Comment by RaulMonteroC** [comment]
Hello!

You catch me on the finishing touches. Sorry for the delay, the edits and the moving things to markdown took a bit more than I had expected.

The pull request #15 is now open and ready for the review

**Comment by claudiosanchez** [comment]
@RaulMonteroC - Thanks for your contribution. Please stay tuned, we will be doing a Live Stream to showcase all of the contributions. I will be tweeting the details in the next 48 hours.
