### ISSUE TITLE
Crashing like a pro with AppCenter

### ISSUE THREAD

**Issue by eatskolnikov** [claudiosanchez/OctoberXamarinChallenge#3]
**Title:** Crashing like a pro with AppCenter
**Author Name:** Enmanuel Toribio
**Twitter Handle:** @eatskolnikov
**Date:** Oct 6
**Abstract:** We have all been there, you build and test your app with all the love in the world,  publish it and then some user comes up with the most obscure of edge cases and the app inevitably crashes. In this article, we will see how to setup AppCenter SDK to make it easier to handle these scenarios, report crashes and how they can help you make a better app.

**Comment by claudiosanchez** [comment]
@eatskolnikov - Your article has been approved. Please be aware that we have moved the challenge to the month of October; please confirm the new date for your article.

**Comment by claudiosanchez** [comment]
@eatskolnikov  Hi there. I have not seen your pull request come in. it was scheduled for Oct 6. Are you still going to submit one?

**Comment by eatskolnikov** [comment]
@claudiosanchez Yes, I'll submit it. I'll have it published by Saturday noon.

**Comment by claudiosanchez** [comment]
@eatskolnikov - Thanks for your contribution. Please stay tuned, we will be doing a Live Stream to showcase all of the contributions. I will be tweeting the details in the next 48 hours.
