### ISSUE TITLE
Xamarin.Forms Design Time Data & Intellisense Tips & Tricks

### ISSUE THREAD

**Issue by jamesmontemagno** [claudiosanchez/OctoberXamarinChallenge#7]
Title: Xamarin.Forms Design Time Data Tips & Tricks
Author Name: James Montemagno
Twitter Handle: @JamesMontemagno
Date: Oct. 10
Abstract: Design time data can easily help you visualize your mobile app and can also assist in Intellisense without having to set the data bindings in your mobile apps directly. In this blog I will walk through simple, advanced, and super advanced tips & tricks for design time data.

**Comment by claudiosanchez** [comment]
@jamesmontemagno - Your article has been approved. Please be aware that we have moved the challenge to the month of October; please confirm the new date for your article.

**Comment by claudiosanchez** [comment]
@jamesmontemagno  Hi there. I have not seen your pull request come in. it was scheduled for Oct 10. Are you still going to submit one?

**Comment by jamesmontemagno** [comment]
https://montemagno.com/xamarin-forms-design-time-data-tips-best-practices/

**Comment by claudiosanchez** [comment]
@jamesmontemagno  - Thanks for your contribution. Please stay tuned, we will be doing a Live Stream to showcase all of the contributions. I will be tweeting the details in the next 48 hours.
