### ISSUE TITLE
Getting Started with Microsoft App Center

### ISSUE THREAD

**Issue by ttirrell** [claudiosanchez/OctoberXamarinChallenge#9]
Title: Getting Started with Microsoft App Center
Author Name: Trevor Tirrell
Twitter Handle: [@trevortirrell](https://twitter.com/TrevorTirrell)
Date: Oct 13
Abstract: I will show how to sign-up for an account, create your app(s) and review the Account Settings.  Then we will add the nuget packages to you project and show you how to initiate the sdk within your project.

**Comment by claudiosanchez** [comment]
@ttirrell  - Your article has been approved. Please be aware that we have moved the challenge to the month of October; please confirm the new date for your article.

**Comment by ttirrell** [comment]
Dates are fine. Thanks

Oct 13

**Comment by ttirrell** [comment]
I submitted a pull request with a markdown file for my blog post. 

http://ttirrell.com/2019/10/getting-started-with-microsoft-app-center/

**Comment by claudiosanchez** [comment]
@ttirrell - Thanks for your contribution. Please stay tuned, we will be doing a Live Stream to showcase all of the contributions. I will be tweeting the details in the next 48 hours.
